#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
chmod +x /app/Rebuild-DNDC*
echo 'alias rebuild="bash /app/Rebuild-DNDC/Rebuild-DNDC.sh"' >> ~/.bashrc
echo 'alias rebuildm="bash /app/Rebuild-DNDC/Rebuild-DNDC-Manual.sh"' >> ~/.bashrc
source ~/.bashrc